### ISSUE TITLE
Доработать алгоритм

### ISSUE THREAD

**Issue by Kasiwadzaki** [balak1ng/lines-splitter#1]
Добрый день, меня зовут Вадим, я разработчик компании Uno-Soft.
  
Алгортим выдает правильный результат по количеству групп, но вот условие по памяти соблюдено не было.  
На файле https://github.com/PeacockTeam/new-job/releases/download/v1.0/lng-4.txt.gz вылетает ошибка OutOfMemoryError. Прошу поправить алгоритм и отписаться по результату в этом issue

**Comment by balak1ng** [comment]
Добрый день!

Алгоритм успешно доработан, теперь условия по памяти -Xmx1G соблюдаются.
